# ---------------------------------------------------------------------------
# copy_supply.py
# Created on: 2012-03-23 16:13:30.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------
##KC original script edited by chadwickk -- all edits indicated by ##KC
##KC uses staging version of CADASTRE in case pre-prod copy hasn't been performed yet

# Import arcpy module
import arcpy, sys, string, os

arcpy.env.overwriteOutput = True
##KCarcpy.env.workspace = "C:\Data\MMS_ExtractForConnect\Assets.gdb"
arcpy.env.workspace = r"C:\Data\CRS\2017_Aug\Assets.gdb" ##KC replaced previous line with this
# Set the configKeyword environment to SDELOB.

#list feature classes
fcl = arcpy.ListFeatureClasses()

#for each in list count and output
for idata in fcl:
    #count records
    fc_count = arcpy.GetCount_management(idata).getOutput(0)
    print idata + " " + fc_count + " Records"

#Delete existing features
arcpy.Delete_management(r"C:\Data\CRS\2017_Aug\Assets.gdb\MX_SPANS","FeatureClass")
arcpy.Delete_management(r"C:\Data\CRS\2017_Aug\Assets.gdb\MX_STRUCTURES","FeatureClass")
arcpy.Delete_management(r"C:\Data\CRS\2017_Aug\Assets.gdb\MX_SITES","FeatureClass")
arcpy.Delete_management(r"C:\Data\CRS\2017_Aug\Assets.gdb\MX_SECTION","FeatureClass")
arcpy.Delete_management(r"C:\Data\CRS\2017_Aug\Assets.gdb\SPAN_Parcel","FeatureClass")
arcpy.Delete_management(r"C:\Data\CRS\2017_Aug\Assets.gdb\STRUCTURE_Parcel","FeatureClass")
arcpy.Delete_management(r"C:\Data\CRS\2017_Aug\Assets.gdb\SITE_Parcel","FeatureClass")
arcpy.Delete_management(r"C:\Data\CRS\2017_Aug\Assets.gdb\Section_Parcel","FeatureClass")
arcpy.Delete_management(r"C:\Data\CRS\2017_Aug\Assets.gdb\CADASTRE","FeatureClass") ##KC added line
##KC print "8 feature classes deleted"
print "9 feature classes deleted" ##KC replaced previous line with this


#Process: Copy Features
arcpy.Copy_management("Database Connections/p_map_user@SPREPORT@SQLPRD-SPATIAL.transpower.co.nz.sde/SPREPORT.MAPDATA.MX_Sites","C:/Data/CRS/2017_Aug/Assets.gdb/MX_Sites","FeatureClass")
arcpy.Copy_management("Database Connections/p_map_user@SPREPORT@SQLPRD-SPATIAL.transpower.co.nz.sde/SPREPORT.MAPDATA.MX_Structures","C:/Data/CRS/2017_Aug/Assets.gdb/MX_Structures","FeatureClass")
arcpy.Copy_management("Database Connections/p_map_user@SPREPORT@SQLPRD-SPATIAL.transpower.co.nz.sde/SPREPORT.MAPDATA.MX_Spans","C:/Data/CRS/2017_Aug/Assets.gdb/MX_Spans","FeatureClass")
##KC arcpy.Copy_management("Database Connections/p_map_user@SPREPORT@SQLPRD-SPATIAL.transpower.co.nz.sde/SPREPORT.MAPDATA.MX_SECTION","C:/Data/MMS_ExtractForConnect/Assets.gdb/MX_SECTION","FeatureClass")
sectionClause = '"status" <> ' + "'FUTURE'" ##KC replaced previous line with this and three following
arcpy.MakeFeatureLayer_management("Database Connections/p_map_user@SPREPORT@SQLPRD-SPATIAL.transpower.co.nz.sde/SPREPORT.MAPDATA.MX_SECTION","sectionLyr",sectionClause) ##KC added line
arcpy.CopyFeatures_management("sectionLyr",r"C:\Data\CRS\2017_Aug\Assets.gdb\MX_SECTION") ##KC added line
arcpy.Copy_management("Database Connections/pp_Dataloader@NZC_STG@NDCSTG_SPAT_AG.transpower.co.nz.sde/NZC_STG.MAPDATA.CADASTRE",r"C:\Data\CRS\2017_Aug\Assets.gdb\CADASTRE","FeatureClass") ##KC added line
##KC print "4 Features copied"
print "5 Features copied" ##KC replaced previous line with this

# Process: Intersect
arcpy.Intersect_analysis("C:/Data/CRS/2017_Aug/Assets.gdb/MX_Structures #;C:/Data/CRS/2017_Aug/Assets.gdb/CADASTRE #","C:/Data/CRS/2017_Aug/Assets.gdb/STRUCTURE_Parcel","ALL","#","POINT")
print "1 Intersect Completed"
arcpy.Intersect_analysis("C:/Data/CRS/2017_Aug/Assets.gdb/MX_Sites #;C:/Data/CRS/2017_Aug/Assets.gdb/CADASTRE #","C:/Data/CRS/2017_Aug/Assets.gdb/SITE_Parcel","ALL","#","POINT")
print "2 Intersects Completed"
arcpy.Intersect_analysis("C:/Data/CRS/2017_Aug/Assets.gdb/MX_Section #;C:/Data/CRS/2017_Aug/Assets.gdb/CADASTRE #","C:/Data/CRS/2017_Aug/Assets.gdb/Section_Parcel","ALL","#","LINE")
print "3 Intersects Completed"
arcpy.Intersect_analysis("C:/Data/CRS/2017_Aug/Assets.gdb/MX_Spans #;C:/Data/CRS/2017_Aug/Assets.gdb/CADASTRE #","C:/Data/CRS/2017_Aug/Assets.gdb/SPAN_Parcel","ALL","#","LINE")
print "All Intersects Completed"

#for each in list count and output
for idata in fcl:
    #count records
    fc_count = arcpy.GetCount_management(idata).getOutput(0)
    print idata + " " + fc_count + " Records"
print arcpy.GetMessages()
