# ---------------------------------------------------------------------------
# copy_supply.py
# Created on: 2012-03-23 16:13:30.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------
##KC original script edited by chadwickk -- all edits indicated by ##KC
##KC uses staging version of CADASTRE in case pre-prod copy hasn't been performed yet

# Import arcpy module
import arcpy, sys, string, os, datetime
import etgLib

starttime = datetime.datetime.now()

arcpy.env.overwriteOutput = True

# script name
script_name = os.path.basename(__file__)

args = []

# variables
fcsToCopy = ['MX_Sites', 'MX_Structures','MX_Spans']
fcsToIntersect = ['MX_Structures', 'MX_Sites', 'MX_Section', 'MX_Spans' ]
outFcs = ['STRUCTURE_Parcel', 'SITE_Parcel', 'Section_Parcel','SPAN_Parcel']
dataTypes = ['POINT', 'POINT', 'LINE', 'LINE']

err_message = None

def crs8_extract_for_connection(args):
    wkgFolder = args[0]
    assetsGDBname = args[1]
    spreportSdePath = args[2]
    spreportDataSDEprefix = args[3]   
    stgSdePath = args[4]
    stgDataSDEprefix = args[5]    
    log = args[6]

    # variables
    err_message = None

    # Set locations, etc
    assetsGDBpath = os.path.join(wkgFolder,assetsGDBname)

    
    try:

        ### Create assets GDB - check for existence first    
        etgLib.log_info(log,'Creating working assets GDB...',True)
        if arcpy.Exists(assetsGDBpath):
            etgLib.log_info(log,'WARNING: {} already exists! - deleted'.format(assetsGDBpath))
            arcpy.Delete_management(assetsGDBpath)
        arcpy.CreateFileGDB_management(wkgFolder,assetsGDBname)

        arcpy.env.workspace = assetsGDBpath
        # Set the configKeyword environment to SDELOB.

        #Process: Copy Features
        etgLib.log_info(log,'Copy Features from SPREPORT database to assets gdb ...',True)
        for fc in fcsToCopy:
            inFCname = spreportDataSDEprefix + fc
            inFCpath = os.path.join(spreportSdePath,inFCname)
            outFCpath = os.path.join(assetsGDBpath,fc)
            etgLib.log_info(log,'Copying: {}'.format(inFCpath))
            if arcpy.Exists(inFCpath):
                arcpy.Copy_management(inFCpath,outFCpath, "FeatureClass")
       
        sectionClause = '"status" <> ' + "'FUTURE'" ##KC replaced previous line with this and three following
        fc_name = spreportDataSDEprefix + "MX_SECTION"
        in_fc = os.path.join(spreportSdePath,fc_name)
        out_fc= os.path.join(assetsGDBpath,fc_name)
        etgLib.delete_layer("sectionLyr")
        arcpy.MakeFeatureLayer_management(in_fc,"sectionLyr",sectionClause)
        etgLib.log_info(log,'Copying: {}'.format(in_fc))
        arcpy.CopyFeatures_management("sectionLyr",out_fc)
      
        etgLib.log_info(log,'Copying staging cadstre ...')
        fc_name = stgDataSDEprefix +"CADASTRE"
        in_fc = os.path.join(stgSdePath,fc_name)
        out_fc = os.path.join(assetsGDBpath,fc_name)
        arcpy.Copy_management(in_fc,out_fc,"FeatureClass") 

        
        # Process: Intersect
        etgLib.log_info(log,'Intersecting ...', True)        
        idx = 0
        for fc in fcsToIntersect:
            in_fcs = [fc, 'CADASTRE']    
            out_fc = outFcs[idx]
            data_type = dataTypes[idx]
            arcpy.Intersect_analysis(in_fcs,out_fc,"ALL","#",data_type)
            etgLib.log_info(log,'Intersecting: {}'.format(in_fcs))
            idx = idx +1

        #for each in list count and output
        etgLib.log_info(log,'checking feature count ...', True)
        fcl = arcpy.ListFeatureClasses()
        for idata in fcl:
            #count records
            fc_count = arcpy.GetCount_management(idata).getOutput(0)
            etgLib.log_info(log,'{0} - {1} Records'.format(idata,fc_count))
        
        etgLib.log_process_time(log,starttime)  

    except Exception as e: 
        err_message =  "ERROR while running {0}: {1}" .format(script_name,e)
    
    return err_message
       